apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: no-access

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daveRoleBiding
subjects:
  - kind: ServiceAccount
    name: dave
roleRef:
  kind: Role
  name: no-access
  apiGroup: rbac.authorization.k8s.io