apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
  containers:
    - name: web
      image: redbull05689/webserver:v3
      livenessProbe:
        tcpSocket: { port: 8000 }
      readinessProbe: # Добавим проверку готовности
        httpGet: 
          path: /index.html # контент
          port: 80
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-index-page
      image: busybox:1.31.0
      command:
        [
          "sh",
          "-c",
          "wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh",
        ]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}